#SPDX-License-Identifier: MIT-0
---
# tasks file for init
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install git
  ansible.builtin.dnf:
    name:
      - git
    state: present

- name: Clone repository
  ansible.builtin.git:
    repo: https://github.com/3yu-qtfd/message_app.git
    dest: "{{ app_dir }}"
    version: main
    accept_hostkey: yes
