#SPDX-License-Identifier: MIT-0
---
# tasks file for init
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Change the timezone
  community.general.timezone:
    name: Asia/Tokyo

