- hosts: all
  become: true

  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Change the timezone
      community.general.timezone:
        name: Asia/Tokyo

#------------------------
#環境構築
#------------------------
#gitインストール

#venvで仮想環境作成

#Flaskインストール

#Gunicornインストール

#gunicorn_conf.py配置

#systemdファイル配置

#Nginxインストール

#nginx.conf配置

#mariadbインストール

#データベース作成→database.pyに書く？

#PyMySQLインストール

#python-dotenvインストール

#.env配置

#------------------------
#アプリ配置
#------------------------
#app.py配置

#index.html配置

#database.py配置


